# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6Olo15zWIknkG_00Esk--CWZqL4PL7U
"""

import streamlit as st
import numpy as np
import pandas as pd
import pickle

# -------------------------------------------------
# LOAD TRAINED MODEL FILES
# -------------------------------------------------

with open("bed_models.pkl", "rb") as f:
    bed_models = pickle.load(f)

with open("constants.pkl", "rb") as f:
    constants = pickle.load(f)

ADenVis = pd.read_csv("density_table.csv")

V_faction = constants["V_faction"]
STD_Density = constants["STD_Density"]

# -------------------------------------------------
# HELPER FUNCTION
# -------------------------------------------------

def get_density(pressure):
    ADen_sorted = ADenVis.sort_values("PArgon")
    return np.interp(
        pressure,
        ADen_sorted["PArgon"],
        ADen_sorted["Density"]
    )

# -------------------------------------------------
# UI
# -------------------------------------------------

st.title("PSA Bed Operation Time Calculator")

bed = st.selectbox("Select Bed", sorted(bed_models.keys()))

diameter = st.number_input("Diameter (in)", min_value=0.01, value=36.0)
height = st.number_input("Height (in)", min_value=0.01, value=120.0)
flow = st.number_input("Flow (scfm)", min_value=0.01, value=100.0)
pressure = st.number_input("Pressure (psig)", min_value=0.01, value=150.0)
concentration = st.number_input("Conc (ppm)", min_value=0.01, value=100.0)

# -------------------------------------------------
# CALCULATION
# -------------------------------------------------

if st.button("Estimate"):

    # Convert geometry
    D_ft = diameter / 12
    H_ft = height / 12

    Vol_tube = np.pi * (D_ft / 2) ** 2 * H_ft
    Cross_section = np.pi * (D_ft / 2) ** 2

    # Density lookup
    AODensity = get_density(pressure)

    # Mass flow (same as notebook)
    AFMass_flow = STD_Density * flow

    # Actual flow
    AFActual_flow = AFMass_flow / AODensity

    # Superficial velocity
    AFSuper_velocity = (
        (AFActual_flow / 60) /
        (V_faction * Cross_section)
    )

    # Prepare regression inputs
    input_df = pd.DataFrame({
        "log_AFSuper_velocity": [np.log(AFSuper_velocity)],
        "log_ACInlet": [np.log(concentration)],
        "log_AOPressure": [np.log(pressure)]
    })

    # Predict
    predicted = bed_models[bed].predict(input_df)[0]

    # Calculate treated volume
    Vol_treated = predicted * Vol_tube

    # Lifetime
    lifetime_min = Vol_treated / flow
    lifetime_hr = lifetime_min / 60
    lifetime_day = lifetime_hr / 24

    # -------------------------------------------------
    # DEBUG OUTPUT (COMPARE WITH NOTEBOOK)
    # -------------------------------------------------

    st.write("Using Bed Model:", bed)
    st.write("Column Volume:", round(Vol_tube, 4), "ft³")
    st.write("Cross-sectional Area:", round(Cross_section, 4), "ft²")
    st.write("Gas Density:", round(AODensity, 6), "lb/ft³")
    st.write("Superficial Velocity:", round(AFSuper_velocity, 6), "ft/s")
    st.write("Predicted Vol_treated_perVol:", round(predicted, 6))

    st.markdown("---")

    st.success("Estimated Lifetime")

    st.write(f"{lifetime_min:.1f} min")
    st.write(f"{lifetime_hr:.2f} hr")
    st.write(f"{lifetime_day:.2f} days")